#!/usr/bin/env bash

if [ -d "${HOME}/.config/fzfrunner/runners" ]; then
  RUNNERS_DIR="${HOME}/.config/fzfrunner/runners"
else
  RUNNERS_DIR="$(dirname "${BASH_SOURCE[0]}")/runners"
fi
ALT_PREFIX="ALT::"

runner_enabled() {
  if [ -f "${HOME}/.config/fzfrunner/config" ]; then
    sed -nr "/^\[runners\]/ { :l /^$1[ ]*=/ { s/.*=[ ]*//; p; q;}; n; b l;}" "${HOME}/.config/fzfrunner/config"
  else
    echo 1
  fi
}

read -r -d '' PY_PRINT <<EOM
import sys

try:
    print(eval(sys.argv[1]))
except:
    pass
EOM

FZF_LIST=""

for f in "${RUNNERS_DIR}"/*; do
  RUNNER="$(echo ${f##*/} | cut -d'.' -f1)"
  if [[ $(runner_enabled "${RUNNER}") == "1" ]]; then
    source "${f}"
    FZF_LIST="${FZF_LIST}$(get_list)"$'\n'
  fi
done

FZF_HISTORY=$(cat "${HOME}/.fzfrunner_history")
FZF_LIST="${FZF_LIST}"$'\n'${FZF_HISTORY}

SELECTED=$(echo "${FZF_LIST}" |
  fzf \
    --print-query \
    --history="${HOME}/.fzfrunner_history"
    --preview-window=down:1 \
    --preview "python <(printf '%s\n' \"${PY_PRINT}\") {q}" \
    --no-info \
    --bind "alt-enter:execute(echo ${ALT_PREFIX}{})+accept")

if [[ "${SELECTED}" =~ ^"${ALT_PREFIX}" ]]; then
  SELECTED=$(echo "${SELECTED}" | head -n1 | sed "s/^${ALT_PREFIX}//")
  ALT=1
else
  SELECTED=$(echo "${SELECTED}" | tail -n1)
  ALT=0
fi

for f in "${RUNNERS_DIR}"/*; do
  RUNNER="$(echo ${f##*/} | cut -d'.' -f1)"
  if [[ $(runner_enabled "${RUNNER}") == "1" ]]; then
    source "${f}"
    if [[ "${SELECTED}" =~ ^"$(get_prefix)" ]]; then
      handle "${SELECTED}" "${ALT}"
      exit 0
    fi
  fi
done
